application: xahcieyei4
version: 1
runtime: java
threadsafe: true

handlers:
#- url: /receiver/*
#  name: Receiver
#  servlet: hu.fnf.devel.onlinecontent.controller.Receiver
#- url: /static/serve*
#  name: Serve
#  servlet: hu.fnf.devel.onlinecontent.controller.Serve
- url: /
  servlet: hu.fnf.devel.onlinecontent.controller.OnlineContentServlet
  name: OnlineContent

#static_files:
#- include: /static/**
#  expiration: 1h

#sessions_enabled: true

#env_variables:
#  DEFAULT_ENCODING: UTF-8

#inbound_services:
#- warmup

#admin_console:
#  pages:
#  - name: Online Games FNF Admin	
#    url: /?admin

# application: my-app
# version: 1
# runtime: java
# threadsafe: true
#
# public_root: /static
#
# static_files:
#  - include: /**
#
# welcome_files:
#  - index.html
#
# system_properties:
#   java.util.logging.config.file: WEB-INF/logging.properties
#  
# handlers:
#   - url: /user/*
#      servlet: org.restlet.ext.servlet.ServerServlet
#      name: user
#      init_params:
#        org.restlet.application: com.my-app.server.resource.user.UserApplication
#        org.restlet.clients: HTTP HTTPS
